[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{subject}}({{ scope }}):{% if show_message %} {{message}}{% endif %}"
example = "feature(brokers): added next_message method to message broker resource"
schema = "<type>(<scope>): <body>"
schema_pattern = "(feat|fix|perf|test|refactor|revert|chore)(\\((ci|repo|cli|lib|tools|release)\\))?: (.+)"

[[tool.commitizen.customize.questions]]
type = "list"
name = "subject"
choices = [
    { value = "feat", name = "feat: A new feature." },
    { value = "fix", name = "fix: A bug fix." },
    { value = "test", name = "test: A changes to tests only." },
    { value = "perf", name = "perf: Performance enhancement that do not impact public API." },
    { value = "refactor", name = "refactor: Changes that do not impact public API." },
    { value = "chore", name = "chore: Anything that does not fit in above categories." },
    { value = "revert", name = "revert: Revert state to a previous commit." },
]
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
choices = [
    { value = "ci", name = "ci: Changes to continous integration stuff." },
    { value = "cli", name = "cli: Changes to command line interface." },
    { value = "lib", name = "lib: Changes to python library." },
    { value = "repo", name = "repo: Changes related to python package and git repository management." },
    { value = "tools", name = "scripts: Changes to tooling and scripts." },
    { value = "tools", name = "release: A release commit (use with chore)." },
]
type = "list"
name = "scope"
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Body."

[[tool.commitizen.customize.questions]]
type = "confirm"
name = "show_message"
message = "Do you want to add body message in commit?"
