name: Release

on:
  push:
    branches:
      - next
      - stable


jobs:
  lint:
    name: Execute semantic release on packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry config virtualenvs.create false
          python -m poetry config virtualenvs.in-project false

      - name: Install python package
        run: |
          CI=1 ./scripts/bootstrap.sh

      - name: Install NodeJS and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install semantic release and its dependencies
        run: |
          k release install

      - name: Perform semantic release
        run: |
          k release do
